name: bdaya_token_auth
description: Handle auth token refresh.
version: 2.0.0-dev.1
homepage: https://github.com/Bdaya-Dev/Flutter-Token-Auth
repository: https://github.com/Bdaya-Dev/Flutter-Token-Auth

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bdaya_repository_pattern: ^3.0.0-dev.1
  jose: ^0.3.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
